### ISSUE TITLE
bin file contains negative number of hashes

### ISSUE THREAD

**Issue by Lexus89** [yanncam/ShuckNT#2] opened 2024-10-10 16:45 UTC
When following the steps I end up with a .bin file that, when loaded, results in a negative number of hashes (-11,770,056). Trying something else; when using the HIBP downloader to get the fresh NTLM hashes, it results in a 77 million database file which unfortunately still cannot find the NTLM hashes for the sample tokens. It seems you have a much larger bin file used by your website (847,223,402), is it perhaps publicly available for download (no idea what that size would be)?  I was hoping that would resolve my issue.. :)

**Comment by yanncam** [comment] 2024-10-10 17:49
Hello @Lexus89,

Do you have tried to download the HIBP-DB (v8) from this mirrorlink (NTLM ordered by hash) ?

```
https://data.verifiedjoseph.com/dataset/pwned-passwords-version-8
```

Sincerely,

**Comment by Lexus89** [comment] 2024-10-10 18:08
Hi @yanncam, yes that's the file I downloaded earlier on. Unfortunately cannot re-download as the mirror isn't working due to a dos attack. Will so give that another shot when it's back again.

**Comment by Lexus89** [comment] 2024-10-15 07:31
Hi @yanncam I just tried it with the file from the mirror, and on both Linux and Windows, and unfortunately it still gives a negative number (#Hash candidates : -11,770,056). Would it be possible to download your .bin file from somewhere?

SHA256 from my BIN file: ac2f6bf681fbe636b94f3ce3f2b594ef3d0af7671375478db1153874e8a5d873

Does yours match (so the problem would be elsewhere)?

**Comment by yanncam** [comment] 2024-10-16 22:40
Hello @Lexus89,

I have generated checksums on my side and the result are the same for the BIN file. So **your final BIN file is ok** :

```
$ sha1sum pwned-passwords-ntlm-*
225a993a908e3d73ffa68859c4f128e17359358e  pwned-passwords-ntlm-ordered-by-hash-v8.7z
4b6c4728c21f64d6a58c7b63d98dcf342c068407  pwned-passwords-ntlm-ordered-by-hash-v8.txt
88094c4a332ecfac9a15c23ba886194d1810b0b2  pwned-passwords-ntlm-ordered-by-hash-v8.txt-reversed
d5486dfbf960f36ff0e1cf313a1b80db5cd4137f  pwned-passwords-ntlm-ordered-by-hash-v8.txt-reversed-sorted
31a5c1b605cca5bcf71196c70f291c05aa3fe86c  pwned-passwords-ntlm-reversed-ordered-by-hash-v8.bin

$ sha256sum pwned-passwords-ntlm-*
ea83d536387e6b149f2e362bf7dfbf521523812611359f47620fd44dae9770ee  pwned-passwords-ntlm-ordered-by-hash-v8.7z
916cfd1772d24f2fe99aa5f37d4a465359c7b6f7d39f45ffbf27deca697b7116  pwned-passwords-ntlm-ordered-by-hash-v8.txt
76f9e101801dfc44489cad4edec5f14d634c2b4676bb9ffbc7e9968c9a5356a5  pwned-passwords-ntlm-ordered-by-hash-v8.txt-reversed
6ee13a35ed88e8073be088a20560cb9fefcc6d08e599241244eaee01dc053a44  pwned-passwords-ntlm-ordered-by-hash-v8.txt-reversed-sorted
ac2f6bf681fbe636b94f3ce3f2b594ef3d0af7671375478db1153874e8a5d873  pwned-passwords-ntlm-reversed-ordered-by-hash-v8.bin
```

Can you try to invoke ShuckNT via PHP-CLI via this command-line (through SSH / shell) ? :

```
$ php shucknt.php -i 'ycam::ad:DEADC0DEDEADC0DE00000000000000000000000000000000:70C249F75FB6D2C0AC2C2D3808386CCAB1514A2095C582ED:1122334455667788' -w pwned-passwords-ntlm-reversed-ordered-by-hash-v8.bin
```

My output reveals the right NT-hash shucked via the BIN file indicated as argument `-w`, so the binary-HIBP-database is well read :

```
[...]

1 hashes-challenges analyzed in 0 seconds, with 1 NT-Hash instantly broken for pass-the-hash and 0 that can be broken via crack.sh for free.

[INPUT] ycam::ad:DEADC0DEDEADC0DE00000000000000000000000000000000:70C249F75FB6D2C0AC2C2D3808386CCAB1514A2095C582ED:1122334455667788
        [NTHASH-SHUCKED] 93B3C62269D55DB9CA660BBB91E2BD0B

[...]
```

About my files size in bytes (to compare with yours) :

```
-rw-r--r-- 1 root  root  12632149389 Oct 16 20:01 pwned-passwords-ntlm-ordered-by-hash-v8.7z
-rw-r--r-- 1 root  root  30564481430 Dec  2  2021 pwned-passwords-ntlm-ordered-by-hash-v8.txt
-rw-r--r-- 1 root  root  30564481430 Oct 16 21:30 pwned-passwords-ntlm-ordered-by-hash-v8.txt-reversed
-rw-r--r-- 1 root  root  30564481430 Oct 16 22:27 pwned-passwords-ntlm-ordered-by-hash-v8.txt-reversed-sorted
-rw-r--r-- 1 root  root  16944468060 Oct 16 23:29 pwned-passwords-ntlm-reversed-ordered-by-hash-v8.bin
```

About lines number for TXT files (to compare with yours) :

```
$ wc -l pwned-passwords-ntlm-ordered-by-hash-v8.txt*
  847223402 pwned-passwords-ntlm-ordered-by-hash-v8.txt
  847223402 pwned-passwords-ntlm-ordered-by-hash-v8.txt-reversed
  847223402 pwned-passwords-ntlm-ordered-by-hash-v8.txt-reversed-sorted
```

About files headers/footers (to compare with yours) :

```
$ head -n 3 pwned-passwords-ntlm-ordered-by-hash-v8.txt*
==> pwned-passwords-ntlm-ordered-by-hash-v8.txt <==
00000001F4A473ED6959F04464F91BB5:4
000000034C209E9CA85D03512759C405:3
0000000CEB20FBC9D76790D7F9E6E22B:1

==> pwned-passwords-ntlm-ordered-by-hash-v8.txt-reversed <==
5BB19F46440F9596DE374A4F10000000:4
504C95721530D58AC9E902C430000000:3
B22E6E9F7D09767D9CBF02BEC0000000:1

==> pwned-passwords-ntlm-ordered-by-hash-v8.txt-reversed-sorted <==
00000008D597FB5AED42B0E7415BF649:18
0000000ABAC115E0C936D4332CF82E6D:8
0000000AEE09130EC9A4EAC92722A2C7:1

$ tail -n 3 pwned-passwords-ntlm-ordered-by-hash-v8.txt*
==> pwned-passwords-ntlm-ordered-by-hash-v8.txt <==
FFFFFFF3837D006BB13987E0963C9BF3:1
FFFFFFF439E17F169BBB2216D9C4E4E6:1
FFFFFFF89C38368724B98C4016622476:4

==> pwned-passwords-ntlm-ordered-by-hash-v8.txt-reversed <==
3FB9C3690E78931BB600D7383FFFFFFF:1
6E4E4C9D6122BBB961F71E934FFFFFFF:1
6742266104C89B42786383C98FFFFFFF:4

==> pwned-passwords-ntlm-ordered-by-hash-v8.txt-reversed-sorted <==
FFFFFFFA841881D8CA88EF528C0FA21B:1
FFFFFFFB0B8D55CA596F8A48700B5074:3
FFFFFFFE1447FDC1799F4047E503D4F2:1
```

I have also try the web mode of ShuckNT by running this command:

```
$ php -S 0.0.0.0:60000 shucknt.php
```

Then going to `http://MYSERVER:60000` to see the ShuckNT web page. The form works well (via sample tokens from `https://github.com/yanncam/ShuckNT/blob/main/tokens-samples.txt`) and the webpage indicated the right number of database's entries:

```
[...]
Current HIBP NT-Hash wordlist used : ./pwned-passwords-ntlm-reversed-ordered-by-hash-v8.bin (#Hash candidates : 847,223,403)
[...]
Results of Hash-Shucking:
10 token(s) analyzed in 4 second(s).
8 NT-Hash instantly shucked! Pass-the-Hash-ready!
1 that can be broken via crack.sh for free!
1 not broken but breakable via crack.sh (non-free) or Hashcat (with time)...
[...]
```

Note : the number of hash candidates indicated via web mode is **847,223,403**, which is the same as the number of line of `pwned-passwords-ntlm-ordered-by-hash-v8.txt` (847,223,402) **+1**. The **+1** is due to a fix for adding the NT-hash `00000000000000000000000000000000` at the top of the binary-database to prevent failure (see this previous issue : https://github.com/yanncam/ShuckNT/issues/1).

Unfortunately, I do not make my binary database file freely available for download due to its (very) large size and the bandwidth consumption of my server that it can generate. This is why I have detailed the methodology on GitHub to generate your own database from the one initially downloadable on the HIBP website (or one of its mirrors).

**But as noted, the sha256sum of your binary file is consistent and identical to mine, so you have the right db !**

Try using ShuckNT in PHP-CLI mode to see if the results are ok.

Keep me informed :) !

Sincerely,

**Comment by Lexus89** [comment] 2024-10-17 06:21
@yanncam It seems my latest BIN file is indeed correct as the hash matches. I notice a difference in Windows/Linux. Earlier on I generated the BINs via Windows, that seemed to result in a different BIN. Now I generated the BIN on Linux and that seemed to go well (despite some "command not found" messages when running shuck from the command line).

Having loaded this correct BIN there is a difference in Windows/Linux when running the tool. Windows shows a negative hash count, but Linux shows the correct one. Wondering if it has something to do with the newline differences when converting to bytes..

Windows:

```
1 hashes-challenges analyzed in 3 seconds, with 0 NT-Hash instantly broken for pass-the-hash and 0 that can be broken via crack.sh for free.

[INPUT] ycam::ad:DEADC0DEDEADC0DE00000000000000000000000000000000:70C249F75FB6D2C0AC2C2D3808386CCAB1514A2095C582ED:1122334455667788
        [CRACK.SH-TOKEN] $NETLM$C85086419358F950$70C249F75FB6D2C0AC2C2D3808386CCAB1514A2095C582ED ($20-$200)
```


Linux:

```
1 hashes-challenges analyzed in 1 seconds, with 1 NT-Hash instantly broken for pass-the-hash and 0 that can be broken via crack.sh for free.

[INPUT] ycam::ad:DEADC0DEDEADC0DE00000000000000000000000000000000:70C249F75FB6D2C0AC2C2D3808386CCAB1514A2095C582ED:1122334455667788
	[NTHASH-SHUCKED] 93B3C62269D55DB9CA660BBB91E2BD0B
```

**Comment by yanncam** [comment] 2024-10-17 08:09
Thanks for this interesting feedback!

During my ShuckNT development phase, I tested the tool to shuck hashes on Windows and Unix/Linux without noticing any problem or bug in use (except for the management of quotes and double-quotes, see the comments of the issue https://github.com/yanncam/ShuckNT/issues/1).

However, the generation of the initial database (reverse / sort / binarize) has always been a step that I performed under Unix/Linux and not Windows.

Indeed, the "reverse" or "binarize" step are carried out by the ShuckNT tool itself, while the "sort" step is delegated to the command present on the distribution.

I have not tested the Windows "sort", and I suspect that your final database is not compatible with ShuckNT because of this.

I will specify in my README.md that the database generation steps must be done via Unix/Linux, and that in general, it is rather recommended to avoid Windows for the use of this tool.

Thanks anyway for the tests and feedback!

**Comment by Lexus89** [comment] 2024-10-17 08:13
You're welcome! The final database that I generated under Linux is as expected, however performing a lookup on Windows still fails. Is that something that could perhaps be fixed? Then Linux is only needed for generating the database one time and lookups can be done on whatever OS is at hand.

`Current HIBP NT-Hash wordlist used : ./pwned-passwords-ntlm-reversed-ordered-by-hash-v8.bin (#Hash candidates : -11,770,056)`

**Comment by yanncam** [comment] 2024-10-17 12:58
Hello again @Lexus89,

I dug into the specific case you mentioned under Windows and I managed to partially reproduce it.

On Windows, with the right binary database (sha256sum ac2f6bf681fbe636b94f3ce3f2b594ef3d0af7671375478db1153874e8a5d873 pwned-passwords-ntlm-reversed-ordered-by-hash-v8.bin), the number of candidate hashes is the right one every time on my side:

```
Current HIBP NT-Hash wordlist used : ./pwned-passwords-ntlm-reversed-ordered-by-hash-v8.bin (#Hash candidates : 847,223,403)
```

I tested with a version of **PHP Version => 8.0.13** and **PHP Version => 8.2.12**.

However, shucking is not identical from one PHP version to another: 

``` 
# PHP 8.0.13: it works well!

1 hashes-challenges analyzed in 0 seconds, with 1 NT-Hash instantly broken for pass-the-hash and 0 that can be broken via crack.sh for free.

[INPUT] ycam::ad:DEADC0DEDEADC0DE00000000000000000000000000000000:70C249F75FB6D2C0AC2C2D3808386CCAB1514A2095C582ED:1122334455667788
        [NTHASH-SHUCKED] 93B3C62269D55DB9CA660BBB91E2BD0B

# PHP 8.2.12: wrong result...

1 hashes-challenges analyzed in 1 seconds, with 0 NT-Hash instantly broken for pass-the-hash and 0 that can be broken via crack.sh for free.

[INPUT] ycam::ad:DEADC0DEDEADC0DE00000000000000000000000000000000:70C249F75FB6D2C0AC2C2D3808386CCAB1514A2095C582ED:1122334455667788
        [CRACK.SH-TOKEN] $NETLM$C85086419358F950$70C249F75FB6D2C0AC2C2D3808386CCAB1514A2095C582ED ($20-$200)
```

For each of these PHP versions, the **openssl** module must be loaded (because it is used by shucknt.php on line 587).

However, there has been a major evolution of the OpenSSL version between these two versions of PHP. Indeed:

* PHP Version => 8.0.13 uses OpenSSL/1.1.1l
* PHP Version => 8.2.12 uses OpenSSL/3.0.11

With OpenSSL3, many cryptographic algorithms have "disappeared" and are no longer usable with the `openssl_encrypt()` function. This is particularly the case for the `DES-ECB` algorithm used by **shucknt.php**, which is no longer part of the list of algorithms returned by `openssl_get_cipher_methods()`.

Consequently, with a recent version of PHP that uses OpenSSL3, the `openssl_encrypt()` function on line 587 of **shucknt.php** returns `false` and impacts the final results.

It is however possible to re-enable the legacy provider of old algorithms (including `DES-ECB`) within OpenSSL3.

I encourage you to consult these resources to do that on Windows:

- https://www.practicalnetworking.net/practical-tls/openssl-3-and-legacy-providers/
- https://stackoverflow.com/questions/73066462/apache-php-installing-cypher-for-openssl-missed-in-openssl-get-cipher-method

Can you try on your side (with a PHP+OpenSSL1 or PHP/OpenSSL3 with legacy provider) ?

Sincerely,

**Comment by Lexus89** [comment] 2024-10-17 14:36
@yanncam Thank you very much for diving into the cause. I can indeed confirm that the PHP and OpenSSL versions are important in this matter. Did a bit more testing and PHP 8.0.13 seems to be the way to go indeed. Looking at the change log of OpenSSL 1.1.1l & 1.1.1m there are no changes resulting in this issue.

PHP Version 8.0.13	OpenSSL/1.1.1l -> Works
PHP Version 8.0.16	OpenSSL 1.1.1m -> Fails
PHP Version 8.1.7	OpenSSL 1.1.1p -> Fails

Will stick with PHP 8.0.13 so all goes well now. Thanks again!

**Comment by yanncam** [comment] 2024-10-17 14:41
Thanks to you for reporting this bug to me, at least the root cause is identified and described in this current issue.

I will think about how to fix the problem in the future directly at the shucknt level (maybe by freeing myself from using the OpenSSL library itself) in a future version.

I allow myself to close this issue and thank you again!

**Closed as completed by yanncam** 2024-10-17 14:41 UTC
